# Site settings
title: Hackers Champloo
author: ハッカーズチャンプルー実行委員会
description: ハッカーズチャンプルー公式サイト

# Jekyll settings
markdown: redcarpet
redcarpet:
  extensions: ['tables', 'autolink', 'no_intra_emphasis']
exclude: ['vendor', 'Gemfile', 'Gemfile.lock']
