# Site settings
title: Hackers Champloo
author: ハッカーズチャンプルー実行委員会
description: ハッカーズチャンプルー公式サイト

google_analytics_tracking_id: UA-41571260-1
domain: hackers-champloo.org

# Jekyll settings
exclude: ['LICENSE', 'CNAME', 'README.md', 'vendor', 'Gemfile', 'Gemfile.lock']

# Plugins
#   Adding Jekyll plugins to a GitHub Pages site - User Documentation
#   https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-sitemap
